AWSTemplateFormatVersion: "2010-09-09"
Description: TestVPC
Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 20.1.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Name
          Value: Test_VPC