AWSTemplateFormatVersion: "2010-09-09"
Description: EX_VPC
Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 30.1.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: name
          Value: EX_VPC
Outputs:
  StackVPC:
    Description: The ID of the VPC
    Value: !Ref myVPC
    Export:
      Name: !Sub "${AWS::StackName}-VPCID"